#ifndef SSTABLE_HANDLER_H
#define SSTABLE_HANDLER_H
#include "cache.h"
#include "log_handler.h"
#include "storage.h"
#include "thread_pool.h"

namespace ozonedb {
// done: sstable handler how to ensure multiple client create different sstable
// the sstable generated by the client can have client fingerprint to differentiate them
// metadata log will be able to identify the order of sstable(the newer one and the old one)

// in sstable, the record type is always kTypeValue
// when compact from the log, will merge the record with the same key,
// if a key only has kTypeValue type, then this record will be ignored.
class SSTableHandler {
 private:
  Storage* storage = nullptr;
  MetadataLogHandler* metadata_log = nullptr;
  std::string sstable_prefix;
  LRUCache* lru_cache = nullptr;
  ThreadPool* thread_pool = nullptr;
  int max_level;
  View const* latest_view = nullptr;

 public:
  /**
   * @brief Construct a new Handler object
   *
   * @param file_size_limit
   * @param log_prefix
   * @param storage
   */
  SSTableHandler(Storage* storage, MetadataLogHandler* metadata_log, std::string sstable_prefix, LRUCache* cache)
      : storage(storage), metadata_log(metadata_log), sstable_prefix(sstable_prefix), lru_cache(cache){};

  // set latest view
  void setLatestView(View const* view) { latest_view = view; }

  // set max level
  void setMaxLevel(int max_level) { this->max_level = max_level; }
  ~SSTableHandler(){};

  Status readRecordFromAllLevel(std::string const& key, Record*& record, std::string const& offset);

  // set thread pool
  void setThreadPool(ThreadPool* thread_pool) { this->thread_pool = thread_pool; }
};
}  // namespace ozonedb
#endif