#ifndef SSTABLE_HANDLER_H
#define SSTABLE_HANDLER_H
#include "cache.h"
#include "storage/file_storage.h"
#include "thread_pool.h"

namespace ozonedb {
// done: sstable handler how to ensure multiple client create different sstable
// the sstable generated by the client can have client fingerprint to differentiate them
// metadata log will be able to identify the order of sstable(the newer one and the old one)

// in sstable, the record type is always kTypeValue
// when compact from the log, will merge the record with the same key,
// if a key only has kTypeValue type, then this record will be ignored.
class SSTableHandler {
 private:
  std::string sstable_prefix;
  LRUCache* lru_cache = nullptr;
  int max_level;
  View* latest_view = nullptr;

 public:
  SSTableHandler(std::string sstable_prefix, LRUCache* cache, int max_level)
      : sstable_prefix(sstable_prefix), lru_cache(cache), max_level(max_level){};

  void setLatestView(View* view) { latest_view = view; }

  ~SSTableHandler(){};

  Status readRecordFromAllLevel(std::string const& key, Record*& record, std::string const& offset);
};
}  // namespace ozonedb
#endif