/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_LazyKVJNI */

#ifndef _Included_jni_LazyKVJNI
#define _Included_jni_LazyKVJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_LazyKVJNI
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_jni_LazyKVJNI_init
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     jni_LazyKVJNI
 * Method:    insert
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_jni_LazyKVJNI_insert
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     jni_LazyKVJNI
 * Method:    update
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_jni_LazyKVJNI_update
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     jni_LazyKVJNI
 * Method:    read
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jni_LazyKVJNI_read
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_LazyKVJNI
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_LazyKVJNI_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
