db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://ozonedb-azuresql-server.database.windows.net:1433;databaseName=ycsb;sendStringParametersAsUnicode=false;
db.user=Xinying
db.passwd=Zxy102246!