sqlite.cache_size=-163840
sqlite.synchronous=FULL
sqlite.journal_mode=WAL
sqlite.create_table=true
sqlite.mmap_size=1000000000
sqlite.page_size=4096
sqlite.begin_concurrent_transactions=true
sqlite.transaction_batch_size=1