db.driver=org.sqlite.JDBC
db.url=jdbc:sqlite:/tank/ycsb_data/sqlite-1KB-workloadc-dur60s/mydb.db?journal_mode=WAL&cache_size=-1048576&synchronous=FULL&mmap_size=1073741824&locking_mode=EXCLUSIVE&vfs=unix-excl
