/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_OzoneDBJNI */

#ifndef _Included_jni_OzoneDBJNI
#define _Included_jni_OzoneDBJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_OzoneDBJNI
 * Method:    openDB
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_OzoneDBJNI_openDB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_OzoneDBJNI
 * Method:    closeDB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_OzoneDBJNI_closeDB
  (JNIEnv *, jobject);

/*
 * Class:     jni_OzoneDBJNI
 * Method:    put
 * Signature: (Ljava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_jni_OzoneDBJNI_put
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     jni_OzoneDBJNI
 * Method:    get
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jni_OzoneDBJNI_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_OzoneDBJNI
 * Method:    remove
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jni_OzoneDBJNI_remove
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_OzoneDBJNI
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_OzoneDBJNI_sync
  (JNIEnv *, jobject);

/*
 * Class:     jni_OzoneDBJNI
 * Method:    clearSync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_OzoneDBJNI_clearSync
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
